baseURL = "https://alecyoung.digital/"
languageCode = "en-us"
title = "Alec Young Tie Yang"
theme = "hugo-developer-portfolio"

[params.plugins]
  # CSS Plugins
  [[params.plugins.css]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/css/uikit.min.css"
  # JS Plugins
  [[params.plugins.js]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/js/uikit.min.js"
  [[params.plugins.js]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/js/uikit-icons.min.js"

[menu]
  [[menu.main]]
  name = "Blog"
  URL = "/blog"


[params]
home = "Home" # What you want the homepage to show up as in the menu bar
# Meta data
description = "Alec Young Tie Yang, 2nd Year student at Supinfo Mauritius"
author = "Alec Young Tie Yang"

  [params.footer]
  email = "alec.youngtieyang98@gmail.com"
  address = "Mauritius"
  googlemaps = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3834469.6661152886!2d55.43126623940809!3d-20.192403389506833!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x217c504df94474c9%3A0x4203d9c2116bd031!2sMaurice!5e0!3m2!1sfr!2smu!4v1596591221098!5m2!1sfr!2smu&output=embed"
